### ISSUE TITLE
Using Broker

### ISSUE THREAD

**Issue by Dmdv** [xpunch/go-micro-example#3]
Question 1.

In these examples there are only the Kafka and MQQT examples.

I've been trying to use example from the base repo but cannot find any example with NATS.
In the base repo the broker package is used:
```
"go-micro.dev/v4/broker"
```

But here you have examples with

```
_ "github.com/asim/go-micro/plugins/broker/kafka/v4"
_ "github.com/asim/go-micro/plugins/broker/mqtt/v4"
"go-micro.dev/v4/client"
```

Question 2.

When I set 
```
  MICRO_BROKER: nats
  MICRO_BROKER_ADDRESS: nats://127.0.0.1:4222
```

I get the following error:

```
file=server/rpc_server.go:834 level=error Broker [nats] connect error: nats: no servers available for connection
```

When I run with arguments:
```
--broker mats --broker_address mats://127.0.0.1:4222
```
The server connects to 4222 successfully but default http broker is used anyways 
¯\_(ツ)_/¯

Is NATS ready to use with micro or I'd rather user the go.nats library for NATS?

**Comment by xpunch** [comment]
Q1:
The workflow for brokers are similar, if you want to use NATS, you can import NATS plugin, then use --broker nats.
If you import multiple broker plugins, means you can switch broker without rebuild your code. My example can work with both kafka and mqtt, that's why I import both kafka and mqtt, case Broker is an abstract interface for asynchronous communication.
Q2:
 nats: no servers available for connection, maybe your nats server does not work fine.
You are spelling mats, should be nats.

**Comment by Dmdv** [comment]
Thank you!
